modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
[[mods]]
modId="cc"
version="${file.jarVersion}"
displayName="Claim Chunk"
displayURL="https://www.curseforge.com/minecraft/mc-mods/claim-chunk"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Claim Chunk'''
[[dependencies.cc]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
